import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import chokidar from "chokidar";
import { resolveI18nConfig, generateDts } from "dialexjs/scanner";
import { logger } from "../utils/logger.js";

export interface GenerateOptions {
  cwd?: string;
  watch?: boolean;
  output?: string;
  config?: string;
  json?: boolean;
}

export function generateDictionaries(
  root: string,
  options: GenerateOptions = {},
): {
  files: string[];
  outputPath: string;
  dtsPath: string;
} {
  const inlineConfig = options.config ? { configFile: options.config } : {};
  const config = resolveI18nConfig(root, inlineConfig);
  const include = config.include || "**/*.content.ts";

  const files = fg.sync(include, {
    cwd: root,
    absolute: true,
    ignore: ["**/node_modules/**", "**/dist/**", "**/.next/**"],
  });

  const srcDir = fs.existsSync(path.join(root, "src")) ? path.join(root, "src") : root;
  const targetOutput = options.output
    ? path.resolve(root, options.output)
    : path.join(srcDir, "dialex.generated.ts");

  const targetDir = path.dirname(targetOutput);

  // 1. Generate TypeScript environment declarations
  generateDts(root, files, config.locales);
  const dtsPath = path.join(srcDir, "dialex-env.d.ts");

  // 2. Build standalone generated module content
  const importLines: string[] = [];
  const dictIdentifiers: string[] = [];

  files.forEach((file, idx) => {
    let rel = path.relative(targetDir, file).replace(/\\/g, "/");
    rel = rel.replace(/\.ts$/, ".js");
    if (!rel.startsWith(".")) {
      rel = "./" + rel;
    }
    const id = `dict_${idx}`;
    importLines.push(`import ${id} from "${rel}";`);
    dictIdentifiers.push(id);
  });

  const dictList =
    dictIdentifiers.length <= 1
      ? `[${dictIdentifiers.join(", ")}]`
      : `[\n  ${dictIdentifiers.join(",\n  ")}\n]`;

  const content = `// Auto-generated by dialex CLI. Do not edit directly.
/* eslint-disable */
// @ts-nocheck
${importLines.join("\n")}

export const dictionaries = ${dictList};

export const dictionaryMap = {
${dictIdentifiers.map((id) => `  [${id}.name]: ${id}.dictionary,`).join("\n")}
};

export default dictionaries;
`;

  fs.mkdirSync(targetDir, { recursive: true });
  const existing = fs.existsSync(targetOutput) ? fs.readFileSync(targetOutput, "utf-8") : "";
  if (existing !== content) {
    fs.writeFileSync(targetOutput, content, "utf-8");
  }

  return { files, outputPath: targetOutput, dtsPath };
}

export async function runGenerate(options: GenerateOptions = {}) {
  const root = options.cwd || process.cwd();
  const quiet = options.json === true;

  const doGenerate = () => {
    try {
      const { files, outputPath, dtsPath } = generateDictionaries(root, options);
      if (quiet) {
        console.log(
          JSON.stringify(
            {
              success: true,
              files: files.map((f) => path.relative(root, f)),
              outputPath: path.relative(root, outputPath),
              dtsPath: path.relative(root, dtsPath),
            },
            null,
            2,
          ),
        );
      } else {
        logger.success(
          `Generated dictionaries for ${files.length} file${files.length === 1 ? "" : "s"}:`,
        );
        logger.info(`→ ${path.relative(root, outputPath)}`);
        logger.info(`→ ${path.relative(root, dtsPath)}`);
      }
      return true;
    } catch (err: any) {
      if (quiet) {
        console.log(
          JSON.stringify(
            {
              success: false,
              error: err.message || String(err),
            },
            null,
            2,
          ),
        );
      } else {
        logger.error(`Generation failed: ${err.message || String(err)}`);
      }
      return false;
    }
  };

  const ok = doGenerate();
  if (!ok && !options.watch) {
    process.exit(1);
  }

  if (options.watch) {
    logger.info("Watching for dictionary changes (-w, --watch)...");
    const inlineConfig = options.config ? { configFile: options.config } : {};
    const config = resolveI18nConfig(root, inlineConfig);
    const pattern = config.include || "**/*.content.ts";

    const watcher = chokidar.watch(pattern, {
      cwd: root,
      ignoreInitial: true,
      ignored: ["**/node_modules/**", "**/dist/**", "**/.next/**"],
    });

    watcher.on("all", (event, filePath) => {
      logger.info(`[${event}] ${filePath} changed, regenerating...`);
      doGenerate();
    });
  }
}
