import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import chokidar from "chokidar";
import { DEFAULT_CONFIG } from "dialexjs";
import { resolveDialexConfig, renderDts } from "dialexjs/scanner";
import { listLocales, parseDictionaryText } from "../utils/dictionary-edit.js";
import { readStaticConfig } from "../utils/static-config.js";
import { relativeImportExtension } from "../utils/tsconfig.js";
import { logger } from "../utils/logger.js";

export interface GenerateOptions {
  cwd?: string;
  watch?: boolean;
  output?: string;
  config?: string;
  json?: boolean;
  /**
   * Read `dialex.config.*` from its syntax tree instead of running it, so no project code
   * executes (used by the editor extension). Settings that are not literals fall back to defaults.
   */
  static?: boolean;
}

const DICTIONARY_IGNORE = ["**/node_modules/**", "**/dist/**", "**/.next/**"];

export interface RenderedGenerate {
  /** Absolute paths of the dictionary files, sorted. */
  files: string[];
  /** Where `dialex.generated.ts` goes, and what it should contain. */
  outputPath: string;
  content: string;
  /** Where `dialex-env.d.ts` goes, and what it should contain (absent without dictionaries). */
  dtsPath: string;
  dtsContent?: string;
  /** The config file that was read, if there is one. Without it every default applies. */
  configFile?: string;
}

/**
 * Works out `dialex.generated.ts` and `dialex-env.d.ts` for a project without writing anything,
 * so `check` can tell whether they are up to date.
 *
 * Settings come from `dialex.config.*` and fall back to {@link DEFAULT_CONFIG}; `locales` falls
 * back to the locales the dictionaries define.
 */
export function renderGenerated(root: string, options: GenerateOptions = {}): RenderedGenerate {
  const inlineConfig = options.config ? { configFile: options.config } : {};
  const staticRead = readStaticConfig(root, options.config);
  const config = options.static ? staticRead.config : resolveDialexConfig(root, inlineConfig);
  const include = config.include || DEFAULT_CONFIG.include;

  const files = fg.sync(include, { cwd: root, absolute: true, ignore: DICTIONARY_IGNORE }).sort();

  const srcDir = fs.existsSync(path.join(root, "src")) ? path.join(root, "src") : root;
  const outputPath = options.output
    ? path.resolve(root, options.output)
    : path.join(srcDir, "dialex.generated.ts");
  const outputDir = path.dirname(outputPath);

  // Read each dictionary's name and locales from its syntax tree; project code is never run.
  const parsed = files.map((file) => parseDictionaryText(file, fs.readFileSync(file, "utf-8")));
  const inferred: string[] = [];
  for (const df of parsed) {
    if (df)
      for (const locale of listLocales(df)) if (!inferred.includes(locale)) inferred.push(locale);
  }
  const locales = config.locales?.length ? config.locales : inferred;

  const clientConfig = {
    defaultLocale: config.defaultLocale || DEFAULT_CONFIG.defaultLocale,
    locales,
    fallbacks: config.fallbacks ?? DEFAULT_CONFIG.fallbacks,
    prefixDefault: config.prefixDefault ?? DEFAULT_CONFIG.prefixDefault,
    lazy: config.lazy ?? DEFAULT_CONFIG.lazy,
  };

  const extension = relativeImportExtension(root);
  const importPath = (file: string) => {
    let rel = path.relative(outputDir, file).replace(/\\/g, "/").replace(/\.ts$/, extension);
    if (!rel.startsWith(".")) rel = "./" + rel;
    return rel;
  };

  const header = `// Auto-generated by dialex CLI. Do not edit directly.
/* eslint-disable */
// @ts-nocheck`;
  const configExport = `export const config = ${JSON.stringify(clientConfig, null, 2)};`;

  let content: string;
  if (clientConfig.lazy) {
    // Only dynamic imports, so bundlers can split each dictionary into its own chunk.
    const loaders = files.map((file, i) => {
      const name = parsed[i]?.name;
      if (!name) {
        throw new Error(
          `Cannot determine the dictionary name of ${path.relative(root, file)} for lazy loading. ` +
            'Use defineDictionary("name", ...) or a literal `name` property.',
        );
      }
      return `  ${JSON.stringify(name)}: () => import("${importPath(file)}"),`;
    });
    content = `${header}

export const dictionaries = [];

export const dictionaryMap = {};

export const loaders = {
${loaders.join("\n")}
};

${configExport}

export const dialex = { dictionaries, config, loaders };

export default dictionaries;
`;
  } else {
    const ids = files.map((_, i) => `dict_${i}`);
    const dictList = ids.length <= 1 ? `[${ids.join(", ")}]` : `[\n  ${ids.join(",\n  ")}\n]`;
    content = `${header}
${files.map((file, i) => `import ${ids[i]} from "${importPath(file)}";`).join("\n")}

export const dictionaries = ${dictList};

export const dictionaryMap = {
${ids.map((id) => `  [${id}.name]: ${id}.dictionary,`).join("\n")}
};

${configExport}

export const dialex = { dictionaries, config };

export default dictionaries;
`;
  }

  const dts = renderDts(root, files, locales);
  return {
    files,
    outputPath,
    content,
    dtsPath: dts?.path ?? path.join(srcDir, "dialex-env.d.ts"),
    dtsContent: dts?.content,
    configFile: staticRead.file,
  };
}

function writeIfChanged(file: string, content: string) {
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf-8") : "";
  if (existing === content) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, "utf-8");
}

export function generateDictionaries(
  root: string,
  options: GenerateOptions = {},
): {
  files: string[];
  outputPath: string;
  dtsPath: string;
  configFile?: string;
} {
  const rendered = renderGenerated(root, options);
  if (rendered.dtsContent !== undefined) writeIfChanged(rendered.dtsPath, rendered.dtsContent);
  writeIfChanged(rendered.outputPath, rendered.content);
  return {
    files: rendered.files,
    outputPath: rendered.outputPath,
    dtsPath: rendered.dtsPath,
    configFile: rendered.configFile,
  };
}

export async function runGenerate(options: GenerateOptions = {}) {
  const root = options.cwd || process.cwd();
  const quiet = options.json === true;

  const doGenerate = () => {
    try {
      const { files, outputPath, dtsPath, configFile } = generateDictionaries(root, options);
      if (quiet) {
        console.log(
          JSON.stringify(
            {
              success: true,
              files: files.map((f) => path.relative(root, f)),
              outputPath: path.relative(root, outputPath),
              dtsPath: path.relative(root, dtsPath),
            },
            null,
            2,
          ),
        );
      } else {
        if (!configFile) {
          logger.info("No dialex.config.* found, using defaults (run `dialex init` to add one).");
        }
        logger.success(
          `Generated dictionaries for ${files.length} file${files.length === 1 ? "" : "s"}:`,
        );
        logger.info(`→ ${path.relative(root, outputPath)}`);
        logger.info(`→ ${path.relative(root, dtsPath)}`);
      }
      return true;
    } catch (err: any) {
      if (quiet) {
        console.log(
          JSON.stringify(
            {
              success: false,
              error: err.message || String(err),
            },
            null,
            2,
          ),
        );
      } else {
        logger.error(`Generation failed: ${err.message || String(err)}`);
      }
      return false;
    }
  };

  const ok = doGenerate();
  if (!ok && !options.watch) {
    process.exit(1);
  }

  if (options.watch) {
    logger.info("Watching for dictionary changes (-w, --watch)...");
    startGenerateWatcher(root, options, doGenerate);
  }
}

const WATCH_IGNORED = /(^|[\\/])(node_modules|dist|\.next|\.nuxt|\.output|\.turbo|\.git)([\\/]|$)/;
const CONFIG_FILE = /(^|[\\/])(dialex|i18n)\.config\.[cm]?[jt]s(on)?$/;

/**
 * Regenerates when a dictionary or config file is added, edited or removed. chokidar 4+ no longer
 * understands globs, so this watches the project directory and decides for itself which events
 * matter, using the same `include` glob as `generate`.
 */
export function startGenerateWatcher(
  root: string,
  options: GenerateOptions,
  regenerate: () => void,
  delay = 100,
) {
  const dictionaryFiles = () => new Set(renderGenerated(root, options).files);
  let known = dictionaryFiles();
  let outputs = new Set<string>();
  let timer: ReturnType<typeof setTimeout> | undefined;

  const trigger = () => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      regenerate();
      try {
        known = dictionaryFiles();
        const rendered = renderGenerated(root, options);
        outputs = new Set([rendered.outputPath, rendered.dtsPath]);
      } catch {
        // keep the previous list; the next event tries again
      }
    }, delay);
  };

  const watcher = chokidar.watch(root, {
    ignoreInitial: true,
    ignored: (file: string) => WATCH_IGNORED.test(file),
  });

  watcher.on("all", (event, filePath) => {
    const file = path.resolve(root, filePath);
    if (outputs.has(file)) return; // our own output
    const isConfig = CONFIG_FILE.test(file);

    if (event === "change") {
      if (!known.has(file) && !isConfig) return;
    } else if (event === "add" || event === "unlink") {
      let now: Set<string>;
      try {
        now = dictionaryFiles();
      } catch {
        return;
      }
      const changed = now.size !== known.size || [...now].some((f) => !known.has(f));
      if (!changed && !isConfig) return;
    } else {
      return;
    }

    logger.info(`[${event}] ${path.relative(root, file)} changed, regenerating...`);
    trigger();
  });

  return watcher;
}
