// Auto-generated by dialex CLI. Do not edit directly.
/* eslint-disable */
// @ts-nocheck
import dict_0 from "./content/common.content";
import dict_1 from "./content/home.content";
import dict_2 from "./content/plurals.content";

export const dictionaries = [dict_0, dict_1, dict_2];

export const dictionaryMap = {
  [dict_0.name]: dict_0.dictionary,
  [dict_1.name]: dict_1.dictionary,
  [dict_2.name]: dict_2.dictionary,
};

export const config = {
  defaultLocale: "en",
  locales: ["en", "tr"],
  fallbacks: {},
  prefixDefault: true,
  lazy: false,
};

export const locales = ["en", "tr"] as const;
export type Locale = (typeof locales)[number];

export const dialex = { dictionaries, config };

export default dictionaries;
