import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import fg from "fast-glob";
import { loadConfigSync } from "unconfig";
import { globalDictionaries, type I18nConfig } from "./index.js";

export function resolveI18nConfig(root: string, inlineConfig: I18nConfig = {}): I18nConfig {
  let loadedConfig: I18nConfig = {};
  try {
    const sources: any[] = [];
    if (inlineConfig.configFile) {
      sources.push({ files: inlineConfig.configFile });
    }
    sources.push(
      {
        files: "dialex.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
      {
        files: "i18n.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
    );

    const result = loadConfigSync<I18nConfig>({
      sources,
      merge: false,
      defaults: {},
      cwd: root,
    });
    if (result && result.config) {
      loadedConfig = result.config;
    }
  } catch {
    // Config fallback
  }

  return {
    defaultLocale: "en",
    include: "**/*.content.ts",
    ...loadedConfig,
    ...inlineConfig,
  };
}

export function generateDts(root: string, files: string[], locales?: string[]) {
  if (files.length === 0) return;

  const dtsDir = fs.existsSync(path.join(root, "src")) ? path.join(root, "src") : root;
  const imports: string[] = [];
  const records: string[] = [];

  files.forEach((file, index) => {
    let relPath = path.relative(dtsDir, file).replace(/\\/g, "/");
    relPath = relPath.replace(/\.ts$/, "");
    if (!relPath.startsWith(".")) {
      relPath = "./" + relPath;
    }

    imports.push(`import dict${index} from '${relPath}';`);
    records.push(
      `Record<typeof dict${index}['name'], typeof dict${index}['dictionary'][keyof typeof dict${index}['dictionary']]>`,
    );
  });

  const localesType =
    locales && locales.length > 0 ? locales.map((l) => `"${l}"`).join(" | ") : "string";

  const dtsContent = `/* eslint-disable */
// @ts-nocheck
// Generated by dialex
${imports.join("\n")}

declare module 'dialex' {
  export interface Register {
    locales: ${localesType};
  }
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/react' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/server' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/hono' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/express' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/fastify' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/koa' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/nestjs' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/elysia' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/sveltekit' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/astro' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/vue' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/web' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/h3' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}

declare module 'dialex/angular' {
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}
`;

  const dtsPath = path.join(dtsDir, "dialex-env.d.ts");
  const existing = fs.existsSync(dtsPath) ? fs.readFileSync(dtsPath, "utf-8") : "";
  if (existing !== dtsContent) {
    fs.mkdirSync(path.dirname(dtsPath), { recursive: true });
    fs.writeFileSync(dtsPath, dtsContent, "utf-8");
  }
}

let scanned = false;

/**
 * Auto-scans all dictionary files (**\/*.content.ts) in the project,
 * imports them into memory, registers them, and ensures TypeScript declaration types are generated.
 */
export async function autoScanAndLoadDictionaries(
  root: string = process.cwd(),
  inlineConfig: I18nConfig = {},
): Promise<Record<string, Record<string, any>>> {
  const config = resolveI18nConfig(root, inlineConfig);
  const include = config.include || "**/*.content.ts";
  const files = fg.sync(include, { cwd: root, absolute: true, ignore: ["**/node_modules/**"] });

  // Generate .d.ts for TypeScript autocompletion
  generateDts(root, files, config.locales);

  // Dynamically load each dictionary into memory if not already done
  if (!scanned) {
    for (const file of files) {
      try {
        const fileUrl = pathToFileURL(file).href;
        await import(fileUrl);
      } catch {
        // Continue if dynamic import is handled elsewhere
      }
    }
    scanned = true;
  }

  return globalDictionaries;
}
