import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import fg from "fast-glob";
import { loadConfigSync } from "unconfig";
import { globalDictionaries, type I18nConfig } from "./index.js";

export function resolveI18nConfig(root: string, inlineConfig: I18nConfig = {}): I18nConfig {
  let loadedConfig: I18nConfig = {};
  try {
    const sources: any[] = [];
    if (inlineConfig.configFile) {
      sources.push({ files: inlineConfig.configFile });
    }
    sources.push(
      {
        files: "dialex.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
      {
        files: "i18n.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
    );

    const result = loadConfigSync<I18nConfig>({
      sources,
      merge: false,
      defaults: {},
      cwd: root,
    });
    if (result && result.config) {
      loadedConfig = result.config;
    }
  } catch {
    // Config fallback
  }

  return {
    defaultLocale: "en",
    include: "**/*.content.ts",
    ...loadedConfig,
    ...inlineConfig,
  };
}

/** Every adapter entry point that has its own `DictionaryRegistry` to augment. */
export const REGISTRY_ADAPTERS = [
  "react",
  "server",
  "hono",
  "express",
  "fastify",
  "koa",
  "nestjs",
  "elysia",
  "sveltekit",
  "astro",
  "vue",
  "web",
  "h3",
  "angular",
] as const;

/** Dependencies that tell which `dialexjs/*` entry points a project can import. */
const ADAPTER_DEPENDENCIES: Record<string, string[]> = {
  react: ["react"],
  "react-dom": ["react"],
  next: ["react", "server"],
  hono: ["hono"],
  express: ["express"],
  fastify: ["fastify"],
  koa: ["koa"],
  "@nestjs/core": ["nestjs"],
  "@nestjs/common": ["nestjs"],
  elysia: ["elysia"],
  "@sveltejs/kit": ["sveltekit"],
  astro: ["astro"],
  vue: ["vue"],
  nuxt: ["vue", "h3"],
  h3: ["h3"],
  nitropack: ["h3"],
  "@angular/core": ["angular"],
  // Frameworks that hand you a standard `Request`, served by `dialexjs/web`.
  "react-router": ["web"],
  "react-router-dom": ["web"],
  "@remix-run/react": ["web"],
  "@remix-run/node": ["web"],
  "@tanstack/react-start": ["web"],
  "@solidjs/start": ["web"],
  wrangler: ["web"],
};

/**
 * The adapter entry points to augment for a project, read from its `package.json`. Falls back to
 * all of them when nothing is recognised, so types never silently go missing.
 */
export function detectAdapters(root: string): string[] {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf-8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies, ...pkg.peerDependencies };
    const found = new Set<string>();
    for (const name of Object.keys(deps)) {
      for (const adapter of ADAPTER_DEPENDENCIES[name] ?? []) found.add(adapter);
    }
    if (found.size > 0) return REGISTRY_ADAPTERS.filter((adapter) => found.has(adapter));
  } catch {
    // no readable package.json
  }
  return [...REGISTRY_ADAPTERS];
}

export function generateDts(root: string, files: string[], locales?: string[]) {
  if (files.length === 0) return;

  const dtsDir = fs.existsSync(path.join(root, "src")) ? path.join(root, "src") : root;
  const imports: string[] = [];
  const records: string[] = [];

  files.forEach((file, index) => {
    let relPath = path.relative(dtsDir, file).replace(/\\/g, "/");
    relPath = relPath.replace(/\.ts$/, "");
    if (!relPath.startsWith(".")) {
      relPath = "./" + relPath;
    }

    imports.push(`import dict${index} from '${relPath}';`);
    records.push(
      `Record<typeof dict${index}['name'], typeof dict${index}['dictionary'][keyof typeof dict${index}['dictionary']]>`,
    );
  });

  const localesType =
    locales && locales.length > 0 ? locales.map((l) => `"${l}"`).join(" | ") : "string";

  const registry = records.join(",\n    ");
  const adapterBlocks = detectAdapters(root)
    .map(
      (adapter) => `
declare module 'dialexjs/${adapter}' {
  export interface DictionaryRegistry extends ${registry} {}
}
`,
    )
    .join("");

  const dtsContent = `/* eslint-disable */
// @ts-nocheck
// Generated by dialex
${imports.join("\n")}

declare module 'dialexjs' {
  export interface Register {
    locales: ${localesType};
  }
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
}
${adapterBlocks}
`;

  const dtsPath = path.join(dtsDir, "dialex-env.d.ts");
  const existing = fs.existsSync(dtsPath) ? fs.readFileSync(dtsPath, "utf-8") : "";
  if (existing !== dtsContent) {
    fs.mkdirSync(path.dirname(dtsPath), { recursive: true });
    fs.writeFileSync(dtsPath, dtsContent, "utf-8");
  }
}

let scanned = false;

/**
 * Auto-scans all dictionary files (**\/*.content.ts) in the project,
 * imports them into memory, registers them, and ensures TypeScript declaration types are generated.
 */
export async function autoScanAndLoadDictionaries(
  root: string = process.cwd(),
  inlineConfig: I18nConfig = {},
): Promise<Record<string, Record<string, any>>> {
  const config = resolveI18nConfig(root, inlineConfig);
  const include = config.include || "**/*.content.ts";
  const files = fg.sync(include, { cwd: root, absolute: true, ignore: ["**/node_modules/**"] });

  // Generate .d.ts for TypeScript autocompletion
  generateDts(root, files, config.locales);

  // Dynamically load each dictionary into memory if not already done
  if (!scanned) {
    for (const file of files) {
      try {
        const fileUrl = pathToFileURL(file).href;
        await import(fileUrl);
      } catch {
        // Continue if dynamic import is handled elsewhere
      }
    }
    scanned = true;
  }

  return globalDictionaries;
}
