// Auto-generated by dialex CLI. Do not edit directly.
/* eslint-disable */
// @ts-nocheck
import dict_0 from "./home.content.js";

export const dictionaries = [dict_0];

export const dictionaryMap = {
  [dict_0.name]: dict_0.dictionary,
};

export const config = {
  defaultLocale: "en",
  locales: ["en", "tr"],
  fallbacks: {},
  prefixDefault: true,
  lazy: false,
};

export const locales = ["en", "tr"] as const;
export type Locale = (typeof locales)[number];

export const dialex = { dictionaries, config };

export default dictionaries;
