// Auto-generated by dialex CLI. Do not edit directly.
/* eslint-disable */
// @ts-nocheck
import dict_0 from "./home.content.js";

export const dictionaries = [dict_0];

export const dictionaryMap = {
  [dict_0.name]: dict_0.dictionary,
};

export default dictionaries;
