import fs from "node:fs";
import path from "node:path";

import { DEFAULT_CONFIG, type DialexConfig } from "dialexjs";
import { loadConfigSync } from "unconfig";

export function resolveDialexConfig(root: string, inlineConfig: DialexConfig = {}): DialexConfig {
  let loadedConfig: DialexConfig = {};
  try {
    const sources: any[] = [];
    if (inlineConfig.configFile) {
      sources.push({ files: inlineConfig.configFile });
    }
    sources.push(
      {
        files: "dialex.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
      {
        files: "i18n.config",
        extensions: ["ts", "mts", "cts", "js", "mjs", "cjs", "json", ""],
      },
    );

    const result = loadConfigSync<DialexConfig>({
      sources,
      merge: false,
      defaults: {},
      cwd: root,
    });
    if (result && result.config) {
      loadedConfig = result.config;
    }
  } catch {
    // Config fallback
  }

  return {
    ...DEFAULT_CONFIG,
    ...loadedConfig,
    ...inlineConfig,
  };
}

/** Every adapter entry point that has its own `DictionaryRegistry` to augment. */
export const REGISTRY_ADAPTERS = [
  "react",
  "server",
  "hono",
  "express",
  "fastify",
  "koa",
  "nestjs",
  "elysia",
  "sveltekit",
  "astro",
  "vue",
  "web",
  "h3",
  "angular",
  "svelte",
  "solid",
] as const;

/** Dependencies that tell which `dialexjs/*` entry points a project can import. */
const ADAPTER_DEPENDENCIES: Record<string, string[]> = {
  react: ["react"],
  "react-dom": ["react"],
  next: ["react", "server"],
  hono: ["hono"],
  express: ["express"],
  fastify: ["fastify"],
  koa: ["koa"],
  "@nestjs/core": ["nestjs"],
  "@nestjs/common": ["nestjs"],
  elysia: ["elysia"],
  "@sveltejs/kit": ["sveltekit"],
  astro: ["astro"],
  vue: ["vue"],
  nuxt: ["vue", "h3"],
  h3: ["h3"],
  nitropack: ["h3"],
  "@angular/core": ["angular"],
  svelte: ["svelte"],
  "solid-js": ["solid"],
  // Frameworks that hand you a standard `Request`, served by `dialexjs/web`.
  "react-router": ["web"],
  "react-router-dom": ["web"],
  "@remix-run/react": ["web"],
  "@remix-run/node": ["web"],
  "@tanstack/react-start": ["web"],
  "@solidjs/start": ["web"],
  wrangler: ["web"],
};

/**
 * The adapter entry points to augment for a project, read from its `package.json`. Falls back to
 * all of them when nothing is recognised, so types never silently go missing.
 */
export function detectAdapters(root: string): string[] {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf-8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies, ...pkg.peerDependencies };
    const found = new Set<string>();
    for (const name of Object.keys(deps)) {
      for (const adapter of ADAPTER_DEPENDENCIES[name] ?? []) found.add(adapter);
    }
    if (found.size > 0) return REGISTRY_ADAPTERS.filter((adapter) => found.has(adapter));
  } catch {
    // no readable package.json
  }
  return [...REGISTRY_ADAPTERS];
}

/**
 * The `dialex-env.d.ts` a project should have: its path and contents, or `undefined` when there
 * are no dictionary files. Nothing is written.
 */
export function renderDts(
  root: string,
  files: string[],
  locales?: string[],
  messageArguments: Record<string, string> = {},
  /** Where to write `dialex-env.d.ts`. Defaults to `src/` when it exists, otherwise `root`. */
  directory?: string,
): { path: string; content: string } | undefined {
  if (files.length === 0) return undefined;

  const dtsDir =
    directory ?? (fs.existsSync(path.join(root, "src")) ? path.join(root, "src") : root);
  const imports: string[] = [];
  const records: string[] = [];

  files.forEach((file, index) => {
    let relPath = path.relative(dtsDir, file).replace(/\\/g, "/");
    relPath = relPath.replace(/\.ts$/, "");
    if (!relPath.startsWith(".")) {
      relPath = "./" + relPath;
    }

    imports.push(`import dict${index} from '${relPath}';`);
    records.push(
      `Record<typeof dict${index}['name'], typeof dict${index}['dictionary'][keyof typeof dict${index}['dictionary']]>`,
    );
  });

  const localesType =
    locales && locales.length > 0 ? locales.map((l) => `"${l}"`).join(" | ") : "string";

  const registry = records.join(",\n    ");
  const messageEntries = Object.entries(messageArguments)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, type]) => `    ${JSON.stringify(key)}: ${type};`)
    .join("\n");
  const adapterBlocks = detectAdapters(root)
    .map(
      (adapter) => `
declare module 'dialexjs/${adapter}' {
  export interface DictionaryRegistry extends ${registry} {}
}
`,
    )
    .join("");

  const dtsContent = `/* eslint-disable */
// @ts-nocheck
// Generated by dialex
${imports.join("\n")}

declare module 'dialexjs' {
  export interface Register {
    locales: ${localesType};
  }
  export interface DictionaryRegistry extends ${records.join(",\n    ")} {}
  export interface MessageArguments {${messageEntries ? `\n${messageEntries}\n  ` : ""}}
}
${adapterBlocks}
`;

  return { path: path.join(dtsDir, "dialex-env.d.ts"), content: dtsContent };
}

export function generateDts(root: string, files: string[], locales?: string[]) {
  const dts = renderDts(root, files, locales);
  if (!dts) return;
  const existing = fs.existsSync(dts.path) ? fs.readFileSync(dts.path, "utf-8") : "";
  if (existing !== dts.content) {
    fs.mkdirSync(path.dirname(dts.path), { recursive: true });
    fs.writeFileSync(dts.path, dts.content, "utf-8");
  }
}
